name: Deploy action
# run-name: ${{ github.actor }} pushed to production 🚀
on:
  push:
    branches:
      - 'main'
      - 'stage'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        run: |
          echo $ssh_key && 
          echo $ssh_key > /tmp/deploy.key && \
          chmod 600 /tmp/deploy.key && \
          apt-get update && \
          apt-get install git && \
          GIT_SSH_COMMAND="ssh -i /tmp/deploy.key -o StrictHostKeyChecking=no" \
          git clone git@gitea.ts.millim.no:${{ github.repository }} . && \
          git checkout ${{ github.ref }}
        with:
          ssh_key: ${{ secrets.DEPLOY_KEY }}
      - name: Install Node
        run: |
          apt-get update && \
          apt-get install -y nodejs
      # - run: cd ${{ github.workspace }}
      - name: Install dependencies
        run: |
          cd veke-frontend
          npm i
      - name: Build frontend
        run: |
          cd veke-frontend
          npm run build
      - name: Install rsync
        run: |
          apt-get update && \
          apt-get install -y ssh rsync
      - name: Fetch the stage target private key
        if: ${{ github.ref == 'refs/heads/stage' }}
        with:
          ssh_key: ${{ secrets.STAGE_PRIVKEY }}
        run: |
          echo "$ssh_key" >> /tmp/target.key
      - name: Deploy to the stage host
        if: ${{ github.ref == 'refs/heads/stage' }}
        env:
          target: ${{ vars.STAGE_HOST }}
        run: |
          chmod -R 777 .
          rsync -a -e "ssh -o \"StrictHostKeyChecking off\" -i /tmp/target.key" --exclude=veke-frontend,venv,secrets,.git ./ $TARGET
      - name: Fetch the deploy target private key
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          ssh_key: ${{ secrets.DEPLOY_PRIVKEY }}
        run: |
          echo "$ssh_key" >> /tmp/target.key
      - name: Deploy to the target host
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          target: ${{ vars.DEPLOY_HOST }}
        run: |
          chmod -R 777 .
          rsync -a -e "ssh -o \"StrictHostKeyChecking off\" -i /tmp/target.key" --exclude=veke-frontend,venv,secrets,.git ./ $TARGET
